server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  main:
    banner-mode: off
      #cloud:
      #gcp:
      #credentials:
      # location: ${googlekeyfile}
      #mvc:
    # hiddenmethod:
    #  filter:
    #   enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    protocol: smtp

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    # "jdbc:mysql://localhost:3306/userDB",
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATASOURCE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      leakDetectionThreshold: 300000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      poolName: RecruitmentZonePool
  threads:
    virtual:
      enabled: true

logging:
  file:
    path: ${LOG_PATH}


mail:
  info: true


rzone:
  to:
    address: ${MAIL_RECIPIENT}

token:
  Secret:
    Key: ${tokenSecretKey}


file:
  directory: ${FILE_DIRECTORY}
#${FILE_DIRECTORY}
upload:
  folder: CANDIDATE_FILES

domain:
  co:
    za: ${DOMAIN}



