version: "3"
services:

  recruitment-zone-application:
    build: .
    image: recruitment-zone
    container_name: recruitment-zone-application
    ports:
      - "8080:8080"
    volumes:
      - recruitment-zone-app-data:/recruitment-zone-app/data



# this section has to be changed after the restore to use an external docker volume
volumes:
  recruitment-zone-db-data:
    driver: local

###
# volumes:
#   uptime-kuma:
#     external: true